// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qyirymysaxxecnymxsur.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF5aXJ5bXlzYXh4ZWNueW14c3VyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwMzM3NjcsImV4cCI6MjA2ODYwOTc2N30.E1mHEVEN3zttJquVUEfJnVi1A2bTLb8PNlE12bCJsLA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});